### ISSUE TITLE
External genlock

### ISSUE THREAD

**Issue by thomasvanta** [breakintoprogram/pico-mposite#1]
Amazing work.
How would you go to use this code with external sync, coming for example from a lm1881.
I guess one could configure interrupts per line and frame.

**Comment by breakintoprogram** [comment]
Thank you.

I would probably start by attaching a sync signal to a GPIO pin and on a separate interrupt flush the FIFO, reset the variables vline and bline, and restart the PIO, to start video generation from scanline 1. Whether that could be done quick enough is a different question.

Hope that helps.
 
I will close this issue as it is outside of the scope of this project.
