### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by MrSurly** [breakintoprogram/pico-mposite#2]
The usual `cmake ..` from `build` doesn't work as expected.  I spent some time trying to fixup the cmake file without any luck.

```
build$ cmake ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:3 (pico_generate_pio_header):
  Unknown CMake command "pico_generate_pio_header".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.18)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/epoulsen/workspaces/pico-mposite/build/CMakeFiles/CMakeOutput.log".
```

**Comment by breakintoprogram** [comment]
Hi, sorry for the delay in getting back to you. What platform are you building it on?

**Comment by MrSurly** [comment]
Hey, no worries -- Ubuntu Linux

**Comment by breakintoprogram** [comment]
Ah, sorry for the delay in getting back to you - you will need to install the Raspberry Pi Pico C/C++ SDK from here:
https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html
There are some custom build steps to assemble the PIO code that require tools from that SDK.

**Comment by orterforth** [comment]
Hi, this is a great project and really shows off PIO. I have the same issue and have tried both Ubuntu and MacOS Catalina. From what I see there is a dependency on pico-examples but I can't see what the correct relationship between them is; whether to clone as a child directory of pico-examples and add as a subdirectory to the pico-examples CMakeFiles.txt, or somehow pass PICO_EXAMPLES_PATH and get it to work that way. (I have tried all of these of course!) Would love to get the terminal mode working and try integrating it into other Pico projects.

**Comment by breakintoprogram** [comment]
Hi @MrSurly @orterforth I've finally gotten around to fixing this - have merged in @kaspervn's changes this afternoon.
