### ISSUE TITLE
Feature idea: YPbPr

### ISSUE THREAD

**Issue by runnerpack** [breakintoprogram/pico-mposite#8]
Most recent TVs (here in the U.S., anyway) have at least one Component (YPbPr) video input.
Maybe the AD724 could be eliminated and the three DACs used to output Y, Pb, and Pr, directly.  I believe "Y" is just RS-170 (grayscale) CVBS, and the other two are mathematically derived from the blue and red channels, respectively, of the original color image, but contain no sync information.
This is less of a request and more of a mention of the idea, in case anyone wants to work on it.  I'd like to give it a try myself, someday, and this project is definitely a huge head-start toward that goal!

**Comment by breakintoprogram** [comment]
Hi @runnerpack that sounds like a great idea, but probably beyond the scope of what I intended to achieve!
